### ISSUE TITLE
Modal with image is not centered first time

### ISSUE THREAD

**Issue by CAM79** [StephanWagner/jBox#130]
Hi Stephan,

Best Modal solution around, I tried many before yours, well done!

Possibly not an issue, hopefully you can help me please:

I've created a modal to display an image (base64), I've set the image in 'content' with an img tag.  On first opening, the modal is not centered.  If the modal is closed and re-opened it is centered, any idea?

Here is the code with all the options I've tried:

	function displayPhoto(id) {
		var photoModal = new jBox('Modal', {
		  content: '<img src="' + photos[id] + '">',
		  width: 'auto',
		  height: 'auto',
		  position: { x: 'center', y: 'center' },
		  repositionOnOpen: true,
		  constructOnInit: true,
		  adjustPosition: true,
		  adjustTracker: true,
		  overlay: true,
		  draggable: 'title',
		  title: 'Photo',
		  theme: 'ModalBorder',
		  closeButton: 'title'
		});
		 
		photoModal.open();
	}

Thanks.

**Comment by StephanWagner** [comment]
Yea, so the problem is that the image is not loaded when jBox opens. Then the image has height="0" and width="0". Therefore jBox calculates the centered position with a content that has no dimension. Then when the image is loaded jBox can calculate the correct position, thats why it works the second time you open it.

There are a few ways to resolve this:

1. Give the image an width and height. e.g.  `content: '<img src="' + photos[id].src + '" width="' + photos[id].width + '" height="' + photos[id].height + '">'`

2. A bit more complicated, but you could add a loader when jBox opens, and then load the image manually. Once the image is loaded, append it to the content area and then call the method `.position()`.

3. See if the image plugin is an option for your case: https://stephanwagner.me/jBox/get_started#images

4. Preload the images

Let me know if you need some more help with one of these options.

**Comment by CAM79** [comment]
Hi Stephan,

Apologies for not getting back to you sooner..

Perfect, thanks for the options.  After researching directly after I posted this, I thought it might be down to missing the width and height, so I'm glad you confirmed it.

Here's the solution I came up with (I don't think I need all the options though!):

		var img = new Image();
		img.src = photos[id];

		img.onload = function() {
			var photoModal = new jBox('Modal', {
		  		content: '<img src="' + photos[id] + '" width="' + img.width + '" height="' + img.height + '" align="middle">',
		  		width: 'auto',
		  		height: 'auto',
		  		position: { x: 'center', y: 'center' },
		  		repositionOnOpen: true,
		  		constructOnInit: true,
		  		adjustPosition: true,
		  		adjustTracker: true,
		  		overlay: true,
		  		draggable: 'title',
		  		title: 'Photo',
		  		theme: 'ModalBorder',
		  		closeButton: 'title'
			});
		 
			photoModal.open();
		}

Thanks.
