### ISSUE TITLE
Modal empty after closing and re-opening

### ISSUE THREAD

**Issue by despecial** [StephanWagner/jBox#154]
See fiddle here: https://jsfiddle.net/2rsdu817/

Works first time. Is empty after closing it and activating again.

**Comment by StephanWagner** [comment]
Thats because `onOpen` is called every time jBox opens. So the second time it opens it will set the content again, but it won't find the element as it was already added, therefore jBox will set an empty content.

You can use `onCreated` instead. This will only get called once jBox was added to DOM. See here: https://jsfiddle.net/StephanWagner/p9t0vx2c/

**Comment by despecial** [comment]
Hey Stephan. Thanks - that fixes it. Very appreciated!

**Comment by redtopia** [comment]
I would like to suggest that you add something about this to the documentation. It's not obvious that when you set the content using a jquery object that it gets removed when the modal is open again, and I didn't find anything in the docs that references this being the case. I would go a step further and suggest that there could be an option to override this behavior.
