### ISSUE TITLE
Multiple instances of jBox Modal Windows

### ISSUE THREAD

**Issue by Tack0** [StephanWagner/jBox#162]
Hello Stefan,

I'm using your example of multiple modal windows (https://jsfiddle.net/StephanWagner/vzh25zph/6/), with little variations,
for instance, i'm setting contents of window using iframe
var VentanasModales = {},
    VentanaModal = 0;

function AbrirVentanajBox(informe, titulo, largo, ancho) {
    if (VentanasModales[VentanaModal]) {
        VentanasModales[VentanaModal].open();
        return null;
    }

	var Options = {
	    id: 'ModalWindow',
	    blockScroll: false,
	    animation: 'zoomIn',
	    draggable: 'title',
	    closeButton: true,
	    overlay: false,
	    reposition: false,
	    repositionOnOpen: false
	};
    
	VentanasModales[VentanaModal] = new jBox('Modal', Options);
	VentanasModales[VentanaModal].setTitle(titulo);
	VentanasModales[VentanaModal].setContent('<iframe src="' + informe + '"></iframe>');
	VentanasModales[VentanaModal].setHeight(ancho);
	VentanasModales[VentanaModal].setWidth(largo);
	VentanasModales[VentanaModal].open();
	VentanaModal++;
};

when it's a single window everything its ok, but the second one appear stack inside the first, i don't know what i'm missing here.

Regards,

Tack0

**Comment by ghaecker** [comment]
Try giving each modal an unique id.

**Comment by Tack0** [comment]
already try it, same behaviour, plus iframe appears cropped inside
jbox content window

2021-02-25 11:55 GMT-05:00, Glenn Haecker <notifications@github.com>:

**Comment by StephanWagner** [comment]
How do you manage the id? Your function `AbrirVentanajBox` will always use the id stored in `VentanaModal `. So it will always create a new instance of jBox. The if test `if (VentanasModales[VentanaModal]) {` will always fail because you add one to the id once it failed the first time. Is that behaviour on purpose?

I adjusted the example here: https://jsfiddle.net/StephanWagner/vzh25zph/26/
There I give each jBox a unique id, so that I can access it later on.

Feel free to adjust the fiddle to reproduce the error you are having.

**Comment by Tack0** [comment]
with a few changes but olved thanks

2021-02-26 6:53 GMT-05:00, Stephan Wagner <notifications@github.com>:
