### ISSUE TITLE
tooltip can not show with method !

### ISSUE THREAD

**Issue by lpyedge** [StephanWagner/jBox#173]
i create a jBox instance,type is tooltip.
but i can not use show() method to show it.

the tooltip show with wrong position on my html page .
some code bellow:

body{position:relative;max-width:10rem;margin:0 auto !important;min-height:100%;display:block;}
#page {width: 100%; height:100%; overflow-y:auto; margin: auto; background: #f5f5f5;}

all my ui is in div#page.the html
the html style 'font-size' max is '54px',when it shows on desktop;

**Comment by lpyedge** [comment]
by the way .
Tippy.js is workd fine on my project,but it dose have modal and notify,
so if jBox can fix the problem,it's good for me.

**Comment by StephanWagner** [comment]
The `.show()` method only works after you have hidden a jBox with `.hide()`.

I just tried to reproduce with your code and I think the problem is that you are resizing the body element: https://jsfiddle.net/StephanWagner/hsmf250k/

That's not best practice, best is to resize a div within the body element, something like that: https://jsfiddle.net/StephanWagner/hsmf250k/8/

Also check out flex-box: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Maybe that will help to create a layout that fills 100% of the viewport height. Resizing the body element usually creates trouble. It's also best practice to let the body element scroll your page.
