### ISSUE TITLE
Tooltip position wrong just first time

### ISSUE THREAD

**Issue by rodoo9** [StephanWagner/jBox#177]
Hi,

I have a jbox tooltip inside a datatables plugin and the first time that the mouse is over the button the tooltip (it's an image) is positioned top-right when it should be center-right, next time it is well positioned. It is happens on all buttons. I use targets,

new jBox('Tooltip', {
            attach: _this,
            target: _target,
            position: {x: "right", y: "center"},
            offset: {x: 5, y: 0},
            outside: 'x'
});

FIRST TIME -> WRONG POSITION
![1](https://user-images.githubusercontent.com/25985734/128762630-087d87ed-a8d5-4dcf-bf97-d5aca4cd56d5.jpg)

NEXT TIMES -> PERFECT AWESOME
![2](https://user-images.githubusercontent.com/25985734/128762636-fe804b1b-c47d-4ccf-bfef-ac2635d7d9db.jpg)

If you need some test, feel free to contact me.

Regards

**Comment by StephanWagner** [comment]
I think thats because it takes some time to load the image. When jbox opens and the image is not loaded, the image has height zero and therefore the calculation of the position calculates with a content height of zero. 

You can try to give the image an height, that should fix the issue. Other than that, the only option i see would be to reposition jBox when the image is loaded.

**Comment by rodoo9** [comment]
Hi, **Solved**. Thank you very much.

I just set width and height properties to the img --> <img src="img_girl.jpg" width="500" height="600">
