### ISSUE TITLE
need alwaysOpen in options , <(＿　＿)>

### ISSUE THREAD

**Issue by andrew781026** [StephanWagner/jBox#180]
Hi,

i am using a jBox tooltip attached to an element with "trigger: click"

i need to control myTooltip all by myself , but it close the myTooltip when i double click the attach element

i add alwaysOpen by myself , it fit my usecase 

![image](https://user-images.githubusercontent.com/10812707/130573184-41fe5ce7-6566-4941-83cc-02bf5e46c3bb.png)

did there possible not to change the jbox.js & It fix my usecase ? 

below is my usecase :  
![2021-08-24_15h27_47](https://user-images.githubusercontent.com/10812707/130575141-60d06d37-3875-47e9-89a3-5e42213dc316.gif)

**Comment by StephanWagner** [comment]
The default behavior is to toggle when clicking. Thats why it closes right away. I'm not sure an alwaysOpen option would be the right approach.

You could try to not attach the jBox and do the opening and closing manually. I tried in your codePen example, but there were too many errors because it uses the attached elements etc. These are not exposed when doing it manually.

Check out this fiddle, thats what I quickly came up with how you would have more control on when the tooltip should open or close:
https://jsfiddle.net/StephanWagner/tvp5L7mw/

**Comment by andrew781026** [comment]
@StephanWagner  thanks for your answering 😊

I found out , I miss use the jbox , the e.stopPropagation()  on input maybe a better way to do so 

```javascript

    // 避免 focus 時 , 再次點擊讓 tooltip 關閉
    $(filterSelect).find('input').on('click', function(e) {

      const isFocus = (this === document.activeElement)
      const isEditMode = (filterSelect.getAttribute('data-mode') === 'edit')
      if (isFocus && isEditMode) {

        e.preventDefault()
        e.stopPropagation()
      }
    })

```

I updated my codepen use case : https://codepen.io/andrew781026/pen/JjNxmxY 🤗
