### ISSUE TITLE
Confirm not posting form

### ISSUE THREAD

**Issue by adambirdie** [StephanWagner/jBox#56]
I am not sure if there is something I am missing but I am unable to post the form after confirm submit is pressed here is my code:

var DeleteAccConfirm = new jBox('Confirm', {

```
confirmButton: 'Yes Delete Account',
cancelButton: 'Hell No My Bad',
maxWidth: 450,
maxHeight: 550,
addClass: 'jBoxDelete',
reposition: true,
setContent: true,
animation: ({
    open: 'slide:bottom',
    close: 'slide:bottom'
}),
confirm: function(){
    $('#delete-account-form').submit();
}
```

});

(function($confirmdeleteacc){
    $confirmdeleteacc.submit(function() {
        DeleteAccConfirm.open();
    });
})($('#delete-account-form'));

**Comment by StephanWagner** [comment]
Sorry for late reply, you probably figured it out by yourself now. I guess it's because you're kinda in a loop here, submitting the form opens a confirm modal which submits the form, which then opens a confirm box, which submits the form, etc. :)

I created a fiddle anyways of how I would do this: http://jsfiddle.net/StephanWagner/cn4921bf/1/
You could always open the confirm box when you submit the form, and then on success create your own form submit function and send the form via ajax.
