### ISSUE TITLE
Multiple tooltips visible at the same time

### ISSUE THREAD

**Issue by dpritula** [StephanWagner/jBox#63]
Hi,

Thank you for the awesome plugin, for your hard work!

I want to report an issue with a multiple tooltips visible at the same time.

Each time I load a portion of DOM via ajax, I'm initializing tooltips on a new loaded container by class selector.
Items which were initialized earlier are triggering tooltip to show on mouse over as normal. But DOM elements with ids of newly created tooltips are positioning below the active tooltip and are shown multiple times.

Could you please take a look?

Cheers!

![untitled-3_03](https://cloud.githubusercontent.com/assets/5113899/12039519/f0cb8ffa-ae69-11e5-8967-b28830a15be8.png)

**Comment by maxicms** [comment]
I have the same problem when using ajax

**Comment by StephanWagner** [comment]
Firstly, sorry for late reply, I've been neglecting jBox for a while and just starting to get back into it since I released jBox v0.4.0

So, there are multiple jBoxes because you are creating multiple. Remember that each time you initialise a jBox you are creating a new instance.

What you want to do is, move the code where you create the instance of jBox from our AJAX response HTML into the page that actually creates the AJAX request. Then, once the AJAX request is successful, reattach the jBox to the new elements that might be in your response HTML.

See this fiddle: http://jsfiddle.net/StephanWagner/cs01uoth/1/
