### ISSUE TITLE
Box closes on Select change

### ISSUE THREAD

**Issue by johnrickman** [StephanWagner/jBox#69]
Title says it all.

**Comment by johnrickman** [comment]
--Fixed--

I was setting the same jquery element to the content as was the owner of the content..

`$('#nodewindow').jBox('Modal', {
					width: 500,
					height: 600,
					content: $('#nodewindow')
				});`

**Comment by StephanWagner** [comment]
Also, consider attaching your jBox with the option attach, rather than using a jQuery selector. I haven't really made a good article about how to best use jBox yet, but using the option attach ist in most cases the better way:

new .jBox('Modal', {
  attach: $('.mySelectorToOpenJBox'),
  width: 500,
  height: 600,
  content: $('#nodewindow')
});

**Comment by johnrickman** [comment]
OK I'll keep that in mind, unfortunately in my scenario the attach items are being dynamically added after the box is setup.

**Comment by StephanWagner** [comment]
Ok, than I would recommend storing your jBox in a global var and reattach the jBox once the elements are added to the DOM, something like that:

```
var myJBOX;

$(document).ready(function () {
  
  // Init jBox and attach to elements already in DOM
  myJBOX = new .jBox('Modal', {
    attach: $('.mySelectorToOpenJBox'),
    width: 500,
    height: 600,
    content: $('#nodewindow')
  });
  
  // Create new element
  $('<div class="mySelectorToOpenJBox"/>').appendTo($('body'));
  
  // Attach jBox to new elements
  myJBOX.attach();
});
```

If you have trouble with anything, let me know or send me some code and I'll have a look at it or make you a fiddle: stephanwagner.me@gmail.com
